package github.weichware10.toolbox.codecharts;

import java.util.ArrayList;
import java.util.Arrays;

/**
* Klasse mit verschidenen Enums fuer den Rasterinhalt.
*/
public class CodeChartsListe {
    /**
     * Liste für die Elemente.
     *
     * @return - Liste mit den Elementen für das Grid
     */
    public static ArrayList<String> getElemente() {
        ArrayList<String> obst = new ArrayList<>(Arrays.asList(
            "Ananas",
            "Apfel",
            "Aprikose",
            "Banane",
            "Birne",
            "Brombeere",
            "Cranberries",
            "Datteln",
            "Erdbereere",
            "Feige",
            "Granatapfel",
            "Grapefruit",
            "Heidelbeeren",
            "Himbeeren",
            "Holunderbeeren",
            "Johannisbeere",
            "Kirsche",
            "Kiwi",
            "Limette",
            "Litschi",
            "Mandarinen",
            "Mango",
            "Melone",
            "Mirabelle",
            "Nashi",
            "Orange",
            "Papaya",
            "Pfirsisch",
            "Physalis",
            "Preiselbeeren",
            "Pomelo",
            "Quitte",
            "Rhabarber",
            "Sanddorn",
            "Stachelbeere",
            "Ugli",
            "Weintrauben",
            "Zitrone",
            "Zwetschge"
        ));

        /*ArrayList<String> gemuese = new ArrayList<>(Arrays.asList(
            "Austernpilze",
            "Aubergine",
            "Blattspinat",
            "Blumenkohl",
            "Bohnen",
            "Brokkoli",
            "Champignons",
            "Chicoree",
            "Chinakohl",
            "Erbsen",
            "Fenchel",
            "Frühlingszwiebel",
            "Grünkohl",
            "Gruke",
            "Kartoffeln",
            "Kohlrabi",
            "Kürbis",
            "Lauch",
            "Mairüben",
            "Mais",
            "Möhren",
            "Paprika",
            "Pastinaken",
            "Petersilienwurzel",
            "Pilze",
            "Radieschen",
            "Rosenkohl",
            "Rote Bete",
            "Rotkohl",
            "Schwarzwurzel",
            "Sellerie",
            "Spargel",
            "Spitzkohl",
            "Steckrüben",
            "Tomaten",
            "Weißkohl",
            "Wirsing",
            "Zucchini",
            "Zwiebel"
        ));

        ArrayList<String> musikgenres = new ArrayList<>(Arrays.asList(
            "Afrobeat",
            "Austropop",
            "Britpop",
            "Elektro Pop",
            "Future Pop",
            "Hip-Hop",
            "Britcore",
            "J-Pop",
            "Mashup",
            "New Wave",
            "Gothic Rock",
            "Neofolk",
            "Neoklassik",
            "Electro Wave",
            "Schlager",
            "Blues",
            "Boogie-Woogie",
            "Funk",
            "Bass Music",
            "Electro",
            "Rap",
            "Jazz",
            "Soul",
            "Calypso",
            "Reggae",
            "Salsa",
            "Tango",
            "Dance",
            "Disco",
            "Dubstep",
            "Grime",
            "IDM",
            "Darkstep",
            "House",
            "Industial",
            "Rave",
            "Schranz",
            "Hardbass",
            "Acidcore",
            "Darkcore",
            "Hardstyle",
            "Jumpstyle",
            "Alternative Rock",
            "Crossover",
            "Grunge",
            "Punk",
            "Artrock",
            "Beatmusik",
            "Deutschrock",
            "Hard Rock",
            "Glam Rock",
            "Rock n Roll",
            "Country Rock",
            "Emo",
            "Trashcore",
            "Metalcore",
            "Metal",
            "Heavy Metal",
            "Dark Metal",
            "Death Metal",
            "Folk Metal",
            "Grindcore",
            "Trash Metal",
            "Ragtime",
            "Swing",
            "Gospel",
            "Ballade",
            "Volksmusik",
            "Irish Folk",
            "Rock"
        ));

        ArrayList<String> filmgenres = new ArrayList<>(Arrays.asList(
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
        ));*/

        return obst;
    }
}
